# Core Network - Virtual Machine - IP address 
network:
    version: 2
    ethernets:
        enp0s3:
            addresses: [192.168.0.101/24]
            dhcp4: false
        enp0s8:
            dhcp4: true
