# Core Network - Virtual Machine - IP address 
network:
    version: 2
    ethernets:
        ens33:
            addresses: [192.168.157.112/24]
            dhcp4: false
        ens37:
            dhcp4: true
